### PR TITLE
remove unused code 

### PR DESCRIPTION
**Pull request by Tsugami**

### CODE REVIEW

**Review by ySnoopyDogy — COMMENTED** [review]
Isn't fs/promisses promise based? So fs.readFile returns a promise, and i need to await it, no?

**Comment by Tsugami** [comment]
> Isn't fs/promisses promise based? So fs.readFile returns a promise, and i need to await it, no?

[`readFile`](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback) await for a callback parameter and [`readFileSync`](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options) returns a promise


I removed async because readFileSync already returns promise and because it's not using await. If a function return an async function, this function will also be an async function

**Review by ySnoopyDogy — CHANGES_REQUESTED** [review]
Can you update the code with the new images? Like the `gado` one. I dont know if i added others than that, but please add new images so i can just merge the updates

**Comment by Tsugami** [comment]
> Can you update the code with the new images? Like the `gado` one. I dont know if i added others than that, but please add new images so i can just merge the updates

done

**Pull request merged**
